apiVersion:  skaffold/v2beta8

kind: Config

deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*

build:
  local:
    push: false

  artifacts:
    - image: callipygious/microstore-auth

      context: auth

      docker:
        dockerfile: Dockerfile

      sync:
        manual:
          - src: 'src/**/*.ts'

            dest: .


    - image: callipygious/microstore-client

      context: client

      docker:
        dockerfile: Dockerfile

      sync:
        manual:
          - src: '**/*.js'

            dest: .


    - image: callipygious/microstore-tickets

      context: tickets

      docker:
        dockerfile: Dockerfile

      sync:
        manual:
          - src: 'src/**/*.ts'

            dest: .
