apiVersion: apps/v1

kind: Deployment

metadata:
  name: orders-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: orders

  template:
    metadata:
      labels:
        app: orders

    spec:
      containers:
        - name: orders

          image: callipygious/microstore-orders

          env:
            - name: JWT_KEY
              valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: JWT_KEY

            - name: MONGO_URI
              value: 'mongodb://orders-mongo-service:27017/orders'

            - name: NATS_URL
              value: 'http://nats-service:4222'

            - name: NATS_CLUSTER_ID
              value: ticketing

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

