apiVersion: v1

kind: Service

metadata:
  name: orders-service

spec:
  type: ClusterIP

  selector:
    app: orders 

  ports:
    - name: orders

      protocol: TCP

      port: 4444

      targetPort: 4444
