apiVersion: apps/v1

kind: Deployment

metadata:
  name: auth-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth

    spec:
      containers:
        - name: auth

          image: callipygious/microstore-auth

          env:
            - name: JWT_KEY
              valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: JWT_KEY

            - name: MONGO_URI
              value: 'mongodb://auth-mongo-service:27017/auth'
